application: djangoapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /sendemail
  script: guestbook.views.taskqueue_mail.app

- url: /.*
  script: main.application

libraries:
- name: django
  version: "latest"

env_variables:
  DJANGO_SETTINGS_MODgULE: 'djangoapp.settings'
